### ISSUE TITLE
URL do site

### ISSUE THREAD

**Issue by joaquimorg** [RadioEscola-pt/radioescola-v1#132]
Em vários locais o endereço do vosso site aponta para https://radioescola.pt mas este não responde e da erro.

Devia responder mesmo não tendo o www.

**Comment by jcalado** [comment]
Olá! Obrigado pelo alerta. Efetivamente temos um problema com domínio que pensamos ter resolvido brevemente.

**Comment by jcalado** [comment]
Problema resolvido.
Obrigado pelo aviso, @joaquimorg
