### ISSUE TITLE
Cor da resposta correta

### ISSUE THREAD

**Issue by teixeiradacunha** [RadioEscola-pt/radioescola-v1#136]
A indicação da resposta correta é apresentada numa cor que no tema escuro é de difícil leitura.

![Capturar](https://github.com/user-attachments/assets/255397b8-1a0c-4132-b9fa-91faa175bf2c)

**Comment by jcalado** [comment]
Penso que já melhorei isto há algum tempo, no entanto admito que o contraste ainda possa ser aumentado.
