### ISSUE TITLE
Diferença na sintaxe das questões json

### ISSUE THREAD

**Issue by alex9099** [RadioEscola-pt/radioescola-v1#14]
Estava a rever por alto o json das questões, 
no ficheiro question1.json linha 3172 há uma mudança de sintaxe, numb passa a ser num e a contagem reinicia, isto não aparenta ser grande problema, mas caso haja erro a carregar as questões o codigo aparenta ir buscar o parametro "numb"

**Comment by dirtybug** [comment]
bem visto vou reparar
