### ISSUE TITLE
separar tutoriais por categoria

### ISSUE THREAD

**Issue by dirtybug** [RadioEscola-pt/radioescola-v1#18]

**Comment by alex9099** [comment]
Documento relevante:
https://www.anacom.pt/streaming/decisaoamador27052009.pdf?contentId=955142&field=ATTACHED_FILE
Anexo 1 (paginas 22-33)

**Comment by alex9099** [comment]
Esta issue ainda não está resolvida,
Vou tratar de criar uma DB para facilitar a integração dos diversos dados

**Comment by alex9099** [comment]
estão separados por categoria de amador mas não por tema, talvez seja ai que estamos a confundir
