### ISSUE TITLE
pass rato por cima as vezes escolhe a categoria errado

### ISSUE THREAD

**Issue by dirtybug** [RadioEscola-pt/radioescola-v1#19]

**Comment by alex9099** [comment]
Consegues descrever melhor o problema? Não consigo reproduzir nada semelhante no firefox 115.0.2 em linux

**Comment by dirtybug** [comment]
sim 
imagina que vais clicar na cat3 e parece que as vezes o rato passa por cima da cat 2 e abre o exame errado.
uma das altercoes e mudar para um drop down que tb poderia ajudar quando for para separar as perguntas por categoria
