### ISSUE TITLE
Pool questões Categoria 1  "uniqueID": 352 > qual é a primeira resposta???

### ISSUE THREAD

**Issue by CS7BAX** [RadioEscola-pt/radioescola-v1#47]
{
            "question": "Qual é o valor de pico da tensão inversa de um rectificador?",
            "answers": [
                "Qual é o valor de pico da tensão inversa de um rectificador?",
                "1,4 vezes a frequência da corrente alternada.",
                "O máximo de tensão suportada pelo rectificador no estado de não-condução.",
                "2,8 vezes a frequência da corrente alternada."
            ],
            "numb": 22,
            "notes": "",
            "correctIndex": 3,
            "img": null,
            "uniqueID": 352
        },

**Comment by CS7BAX** [comment]
Esta Pergunta não pertence a bateria de perguntas da anacom e não foi validada em testes, Questiono a fonte??

**Comment by CS7BAX** [comment]
Resolvido parcialmente , foi retirada a questão e está a guardar que volte a aparecer novamente em exame

**Comment by alex9099** [comment]
até que apareça novamente e dado já ter sido removida do banco de questões, esta issue fica fechada
