### ISSUE TITLE
Conteúdo: Antenas

### ISSUE THREAD

**Issue by jcalado** [RadioEscola-pt/radioescola-v1#93]

**Comment by CS7BAX** [comment]
Já dei o meu contributo para o capitulo das Antenas.

Joel quando puderes é dar ai um toque na formatação e no estilo, tentei aplicar alguma coisa mas falta ai o teu dedo :)

Seria interesante uma vez que é um documento algo extenso colocares uma tabela de conteudos semelhante o que temos para as "Entidades e suas competências"

![image](https://github.com/RadioEscola-pt/radioescola/assets/102839724/c3ce8a34-e070-4b3c-9e94-7d8a912e96e3)

Espero que gostem... e como diz o Julio "não está escrito e pedra" é alterar o que se achar conveniente.
