### ISSUE TITLE
o pdf do swr o conteudo esta no html

### ISSUE THREAD

**Issue by dirtybug** [RadioEscola-pt/radioescola-v1#97]
pode-se de remover o pdf?

**Comment by alex9099** [comment]
Diria que não, o objetivo é manter a fonte

**Comment by CS7BAX** [comment]
Eu também deixava ficar. Esse documento que fiz creio que evidencia melhor a utilização de das duas formulas e também tem os calculos decompostos, não quer dizer que o que que fizeste esteja mal  a verdade é que se complementam, quem conseguir chegar lá o com a parte web tudo bem, quem não perceber e for consultar o pdf com as continhas todas pode perceber dessa forma.
